version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:794638943793:task-definition/my-ecs-frontend-task-definition:15"
        LoadBalancerInfo:
          ContainerName: "frontend"
          ContainerPort: 80